stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package

test:
  stage: test
  image: maven:3.3.9-jdk-8
  script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
  coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
  stage: checkstyle
  image: maven:3.3.9-jdk-8
  script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
  DB_IP: ec2-54-154-101-45.eu-west-1.compute.amazonaws.com
  DB_PORT: 5432
  DB_USER: bdfplwctnqrpsc
  DB_PASSWORD: 3a04fa94bb72e5bd3fe1b5c725ec778e8d36a4330a0cfb9b0b81ecffd9ed8b72
  DB_DBNAME: d7arje351q9hod

deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=demo-spring-sd2021-kaj --api-key=$HEROKU_API_KEY
  only:
    - main
